chore: support pytest

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -69,12 +69,22 @@ jobs:
               run: |
                 mkdir app
                 >app/__main__.py echo -e 'import requests\nprint(requests.get("https://api.github.com").text)'
+                >app/app_test.py echo -e 'def test_bad():\n  assert 1 == 2'
                 sed -i 's/dependencies = \[/dependencies = ["requests",/' pyproject.toml
                 ./repin.sh
                 bazel run //app:app_bin
               working-directory: "${{ steps.scaffold.outputs.dir }}"
               if: "${{ matrix.preset == 'py' }}"
-            
+            - name: Python test that fails
+              continue-on-error: true # for some reason `bazel test || true` still failing.
+              run: bazel test //app:app_test
+              working-directory: "${{ steps.scaffold.outputs.dir }}"
+              if: "${{ matrix.preset == 'py' }}"
+            - name: Check failure is expected
+              run: grep "FAILED app/app_test.py::test_bad - assert 1 == 2" $(bazel info bazel-testlogs)/app/app_test/test.log
+              working-directory: "${{ steps.scaffold.outputs.dir }}"
+              if: "${{ matrix.preset == 'py' }}"
+
             - name: Go smoke test
               run: ./tools/go mod tidy
               working-directory: "${{ steps.scaffold.outputs.dir }}"
